set(CMAKE_SYSTEM_NAME lm32)
set(CMAKE_SYSTEM_PROCESSOR lm32)

set( CMAKE_FIND_ROOT_PATH $ENV{OECORE_TARGET_SYSROOT} )
set( CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER )
set( CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY )
set( CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY )
set( CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY )
set(CMAKE_FIND_LIBRARY_CUSTOM_LIB_SUFFIX "$ENV{OE_CMAKE_FIND_LIBRARY_CUSTOM_LIB_SUFFIX}")

set(CMAKE_C_COMPILER $ENV{OECORE_NATIVE_SYSROOT}/usr/bin/lm32-elf-gcc)
# set(CMAKE_CXX_COMPILER "")
set(CMAKE_C_COMPILER_TARGET lm32-elf)
set(CMAKE_CXX_COMPILER_TARGET lm32-elf)
set(CMAKE_OBJCOPY $ENV{OECORE_NATIVE_SYSROOT}/usr/bin/lm32-elf-objcopy)

# set linker flags
set(CMAKE_EXE_LINKER_FLAGS "-nostdlib -lgcc -lc")

