pipeline {
    agent any
    options {
        quietPeriod(0)
    }

    stages {
        stage('Build') {
            steps {
                sh "./scripts/build.sh"
            }
        }
    }
    post {
        always {
            archiveArtifacts artifacts: 'out/dm-cmd,out/dm-sched,out/libcarpedm.*,out/replaceChain,out/ftm.bin,out/ftm.elf,out/Generator_DU', fingerprint: true
        }
    }
}
