FROM 192.168.1.100:5000/timing/ftm-builder:latest as builder

ARG USER_UID=1000
ARG USER_GID=1000
ARG USERNAME=vscode

RUN USERNAME=${USERNAME} \
    && USER_UID=${USER_UID} \
    && USER_GID=${USER_GID} \
    && groupadd --gid $USER_GID $USERNAME \
    && useradd -s /bin/bash --uid $USER_UID --gid $USER_GID -m $USERNAME

# Create .vscode-server directory
RUN mkdir -p /home/$USERNAME/.vscode-server \
    && chown -R $USERNAME:$USERNAME /home/$USERNAME/.vscode-server

USER $USERNAME