FROM localhost/ftm-builder:latest as builder
# Install dev tools
RUN apt-get update && \
    apt-get install -y \
    gdb \
    git \
    python3-dev \
    python3-pip \
    python3-setuptools \
    python3-wheel \
    pipx \
    cmake \
    libboost-dev \
    libboost-serialization-dev \
    libboost-graph-dev \
    pkg-config \
    libxml2-dev

ARG USER_UID=1000
ARG USER_GID=1000
ARG USERNAME=vscode

RUN USERNAME=${USERNAME} \
    && USER_UID=${USER_UID} \
    && USER_GID=${USER_GID} \
    && groupadd --gid $USER_GID $USERNAME \
    && useradd -s /bin/bash --uid $USER_UID --gid $USER_GID -m $USERNAME

# Create .vscode-server directory
RUN mkdir -p /home/$USERNAME/.vscode-server \
    && chown -R $USERNAME:$USERNAME /home/$USERNAME/.vscode-server

USER $USERNAME

RUN pipx ensurepath && pipx install poetry