Feature: Add Download Compare
    Scenario Outline: Add <schedule> and compare with itself
        Given we add schedules
            | name        |
            | <schedule>  |
        When we run the schedule "patternA"
        Then the device should have the schedule <schedule>
        When we only keep the schedule <schedule>
        Then the device should have the schedule <schedule>
    Examples:
        | schedule          |
        | testSingleEdge-blockalign-blockalign-altdst |
        | testSingleEdge-blockalign-blockalign-defdst |
        | testSingleEdge-blockalign-blockalign-reference |
        | testSingleEdge-blockalign-blockalign-reference-thread32 |
        | testSingleEdge-blockalign-block-altdst |
        | testSingleEdge-blockalign-block-defdst |
        | testSingleEdge-blockalign-block-reference |
        | testSingleEdge-blockalign-block-reference-thread32 |
        | testSingleEdge-blockalign-flow-altdst |
        | testSingleEdge-blockalign-flow-defdst |
        | testSingleEdge-blockalign-flow-reference |
        | testSingleEdge-blockalign-flow-reference-thread32 |
        | testSingleEdge-blockalign-flush-altdst |
        | testSingleEdge-blockalign-flush-defdst |
        | testSingleEdge-blockalign-flush-reference |
        | testSingleEdge-blockalign-flush-reference-thread32 |
        | testSingleEdge-blockalign-global-altdst |
        | testSingleEdge-blockalign-global-defdst |
        | testSingleEdge-blockalign-global-reference |
        | testSingleEdge-blockalign-global-reference-thread32 |
        | testSingleEdge-blockalign-noop-altdst |
        | testSingleEdge-blockalign-noop-defdst |
        | testSingleEdge-blockalign-noop-reference |
        | testSingleEdge-blockalign-noop-reference-thread32 |
        | testSingleEdge-blockalign-origin-altdst |
        | testSingleEdge-blockalign-origin-defdst |
        | testSingleEdge-blockalign-origin-reference |
        | testSingleEdge-blockalign-origin-reference-thread32 |
        | testSingleEdge-blockalign-startthread-altdst |
        | testSingleEdge-blockalign-startthread-defdst |
        | testSingleEdge-blockalign-startthread-reference |
        | testSingleEdge-blockalign-startthread-reference-thread32 |
        | testSingleEdge-blockalign-switch-altdst |
        | testSingleEdge-blockalign-switch-defdst |
        | testSingleEdge-blockalign-switch-reference |
        | testSingleEdge-blockalign-switch-reference-thread32 |
        | testSingleEdge-blockalign-tmsg-altdst |
        | testSingleEdge-blockalign-tmsg-defdst |
        | testSingleEdge-blockalign-tmsg-reference |
        | testSingleEdge-blockalign-tmsg-reference-thread32 |
        | testSingleEdge-blockalign-wait-altdst |
        | testSingleEdge-blockalign-wait-defdst |
        | testSingleEdge-blockalign-wait-reference |
        | testSingleEdge-blockalign-wait-reference-thread32 |
        | testSingleEdge-block-blockalign-altdst |
        | testSingleEdge-block-blockalign-defdst |
        | testSingleEdge-block-blockalign-reference |
        | testSingleEdge-block-blockalign-reference-thread32 |
        | testSingleEdge-block-block-altdst |
        | testSingleEdge-block-block-defdst |
        | testSingleEdge-block-block-reference |
        | testSingleEdge-block-block-reference-thread32 |
        | testSingleEdge-block-flow-altdst |
        | testSingleEdge-block-flow-defdst |
        | testSingleEdge-block-flow-reference |
        | testSingleEdge-block-flow-reference-thread32 |
        | testSingleEdge-block-flush-altdst |
        | testSingleEdge-block-flush-defdst |
        | testSingleEdge-block-flush-reference |
        | testSingleEdge-block-flush-reference-thread32 |
        | testSingleEdge-block-global-altdst |
        | testSingleEdge-block-global-defdst |
        | testSingleEdge-block-global-reference |
        | testSingleEdge-block-global-reference-thread32 |
        | testSingleEdge-block-noop-altdst |
        | testSingleEdge-block-noop-defdst |
        | testSingleEdge-block-noop-reference |
        | testSingleEdge-block-noop-reference-thread32 |
        | testSingleEdge-block-origin-altdst |
        | testSingleEdge-block-origin-defdst |
        | testSingleEdge-block-origin-reference |
        | testSingleEdge-block-origin-reference-thread32 |
        | testSingleEdge-block-startthread-altdst |
        | testSingleEdge-block-startthread-defdst |
        | testSingleEdge-block-startthread-reference |
        | testSingleEdge-block-startthread-reference-thread32 |
        | testSingleEdge-block-switch-altdst |
        | testSingleEdge-block-switch-defdst |
        | testSingleEdge-block-switch-reference |
        | testSingleEdge-block-switch-reference-thread32 |
        | testSingleEdge-block-tmsg-altdst |
        | testSingleEdge-block-tmsg-defdst |
        | testSingleEdge-block-tmsg-reference |
        | testSingleEdge-block-tmsg-reference-thread32 |
        | testSingleEdge-block-wait-altdst |
        | testSingleEdge-block-wait-defdst |
        | testSingleEdge-block-wait-reference |
        | testSingleEdge-block-wait-reference-thread32 |
        | testSingleEdge-flow-blockalign-defdst |
        | testSingleEdge-flow-blockalign-flowdst |
        | testSingleEdge-flow-blockalign-target |
        | testSingleEdge-flow-block-defdst |
        | testSingleEdge-flow-block-flowdst |
        | testSingleEdge-flow-block-target |
        | testSingleEdge-flow-flow-defdst |
        | testSingleEdge-flow-flow-flowdst |
        | testSingleEdge-flow-flush-defdst |
        | testSingleEdge-flow-flush-flowdst |
        | testSingleEdge-flow-noop-defdst |
        | testSingleEdge-flow-noop-flowdst |
        | testSingleEdge-flow-origin-defdst |
        | testSingleEdge-flow-origin-flowdst |
        | testSingleEdge-flow-startthread-defdst |
        | testSingleEdge-flow-startthread-flowdst |
        | testSingleEdge-flow-switch-defdst |
        | testSingleEdge-flow-switch-flowdst |
        | testSingleEdge-flow-tmsg-defdst |
        | testSingleEdge-flow-tmsg-flowdst |
        | testSingleEdge-flow-wait-defdst |
        | testSingleEdge-flow-wait-flowdst |
        | testSingleEdge-flush-blockalign-defdst |
        | testSingleEdge-flush-blockalign-flushovr |
        | testSingleEdge-flush-blockalign-target |
        | testSingleEdge-flush-block-defdst |
        | testSingleEdge-flush-block-flushovr |
        | testSingleEdge-flush-block-target |
        | testSingleEdge-flush-flow-defdst |
        | testSingleEdge-flush-flow-flushovr |
        | testSingleEdge-flush-flush-defdst |
        | testSingleEdge-flush-flush-flushovr |
        | testSingleEdge-flush-global-defdst |
        | testSingleEdge-flush-global-flushovr |
        | testSingleEdge-flush-noop-defdst |
        | testSingleEdge-flush-noop-flushovr |
        | testSingleEdge-flush-origin-defdst |
        | testSingleEdge-flush-origin-flushovr |
        | testSingleEdge-flush-startthread-defdst |
        | testSingleEdge-flush-startthread-flushovr |
        | testSingleEdge-flush-switch-defdst |
        | testSingleEdge-flush-switch-flushovr |
        | testSingleEdge-flush-tmsg-defdst |
        | testSingleEdge-flush-tmsg-flushovr |
        | testSingleEdge-flush-wait-defdst |
        | testSingleEdge-flush-wait-flushovr |
        | testSingleEdge-noop-blockalign-defdst |
        | testSingleEdge-noop-blockalign-target |
        | testSingleEdge-noop-block-defdst |
        | testSingleEdge-noop-block-target |
        | testSingleEdge-noop-flow-defdst |
        | testSingleEdge-noop-flush-defdst |
        | testSingleEdge-noop-noop-defdst |
        | testSingleEdge-noop-origin-defdst |
        | testSingleEdge-noop-startthread-defdst |
        | testSingleEdge-noop-switch-defdst |
        | testSingleEdge-noop-tmsg-defdst |
        | testSingleEdge-noop-wait-defdst |
        | testSingleEdge-origin-blockalign-defdst |
        | testSingleEdge-origin-blockalign-origindst |
        | testSingleEdge-origin-block-defdst |
        | testSingleEdge-origin-block-origindst |
        | testSingleEdge-origin-flow-defdst |
        | testSingleEdge-origin-flow-origindst |
        | testSingleEdge-origin-flush-defdst |
        | testSingleEdge-origin-flush-origindst |
        | testSingleEdge-origin-global-defdst |
        | testSingleEdge-origin-global-origindst |
        | testSingleEdge-origin-noop-defdst |
        | testSingleEdge-origin-noop-origindst |
        | testSingleEdge-origin-origin-defdst |
        | testSingleEdge-origin-origin-origindst |
        | testSingleEdge-origin-startthread-defdst |
        | testSingleEdge-origin-startthread-origindst |
        | testSingleEdge-origin-switch-defdst |
        | testSingleEdge-origin-switch-origindst |
        | testSingleEdge-origin-tmsg-defdst |
        | testSingleEdge-origin-tmsg-origindst |
        | testSingleEdge-origin-wait-defdst |
        | testSingleEdge-origin-wait-origindst |
        | testSingleEdge-startthread-blockalign-defdst |
        | testSingleEdge-startthread-block-defdst |
        | testSingleEdge-startthread-flow-defdst |
        | testSingleEdge-startthread-flush-defdst |
        | testSingleEdge-startthread-global-defdst |
        | testSingleEdge-startthread-noop-defdst |
        | testSingleEdge-startthread-origin-defdst |
        | testSingleEdge-startthread-startthread-defdst |
        | testSingleEdge-startthread-switch-defdst |
        | testSingleEdge-startthread-tmsg-defdst |
        | testSingleEdge-startthread-wait-defdst |
        | testSingleEdge-switch-blockalign-defdst |
        | testSingleEdge-switch-blockalign-switchdst |
        | testSingleEdge-switch-blockalign-target |
        | testSingleEdge-switch-block-defdst |
        | testSingleEdge-switch-block-switchdst |
        | testSingleEdge-switch-block-target |
        | testSingleEdge-switch-flow-defdst |
        | testSingleEdge-switch-flow-switchdst |
        | testSingleEdge-switch-flush-defdst |
        | testSingleEdge-switch-flush-switchdst |
        | testSingleEdge-switch-global-defdst |
        | testSingleEdge-switch-global-switchdst |
        | testSingleEdge-switch-noop-defdst |
        | testSingleEdge-switch-noop-switchdst |
        | testSingleEdge-switch-origin-defdst |
        | testSingleEdge-switch-origin-switchdst |
        | testSingleEdge-switch-startthread-defdst |
        | testSingleEdge-switch-startthread-switchdst |
        | testSingleEdge-switch-switch-defdst |
        | testSingleEdge-switch-switch-switchdst |
        | testSingleEdge-switch-tmsg-defdst |
        | testSingleEdge-switch-tmsg-switchdst |
        | testSingleEdge-switch-wait-defdst |
        | testSingleEdge-switch-wait-switchdst |
        | testSingleEdge-tmsg-blockalign-defdst |
        | testSingleEdge-tmsg-blockalign-dynpar0-3cpu |
        | testSingleEdge-tmsg-blockalign-dynpar0-3cpu-thread32 |
        | testSingleEdge-tmsg-blockalign-dynpar0 |
        | testSingleEdge-tmsg-blockalign-dynpar0-thread32 |
        | testSingleEdge-tmsg-blockalign-dynpar1-3cpu |
        | testSingleEdge-tmsg-blockalign-dynpar1-3cpu-thread32 |
        | testSingleEdge-tmsg-blockalign-dynpar1 |
        | testSingleEdge-tmsg-blockalign-dynpar1-thread32 |
        | testSingleEdge-tmsg-blockalign-reference |
        | testSingleEdge-tmsg-blockalign-reference-thread32 |
        | testSingleEdge-tmsg-block-defdst |
        | testSingleEdge-tmsg-block-dynpar0-3cpu |
        | testSingleEdge-tmsg-block-dynpar0-3cpu-thread32 |
        | testSingleEdge-tmsg-block-dynpar0 |
        | testSingleEdge-tmsg-block-dynpar0-thread32 |
        | testSingleEdge-tmsg-block-dynpar1-3cpu |
        | testSingleEdge-tmsg-block-dynpar1-3cpu-thread32 |
        | testSingleEdge-tmsg-block-dynpar1 |
        | testSingleEdge-tmsg-block-dynpar1-thread32 |
        | testSingleEdge-tmsg-block-reference |
        | testSingleEdge-tmsg-block-reference-thread32 |
        | testSingleEdge-tmsg-flow-defdst |
        | testSingleEdge-tmsg-flow-dynpar0-3cpu |
        | testSingleEdge-tmsg-flow-dynpar0-3cpu-thread32 |
        | testSingleEdge-tmsg-flow-dynpar0 |
        | testSingleEdge-tmsg-flow-dynpar0-thread32 |
        | testSingleEdge-tmsg-flow-dynpar1-3cpu |
        | testSingleEdge-tmsg-flow-dynpar1-3cpu-thread32 |
        | testSingleEdge-tmsg-flow-dynpar1 |
        | testSingleEdge-tmsg-flow-dynpar1-thread32 |
        | testSingleEdge-tmsg-flow-reference |
        | testSingleEdge-tmsg-flow-reference-thread32 |
        | testSingleEdge-tmsg-flush-defdst |
        | testSingleEdge-tmsg-flush-dynpar0-3cpu |
        | testSingleEdge-tmsg-flush-dynpar0-3cpu-thread32 |
        | testSingleEdge-tmsg-flush-dynpar0 |
        | testSingleEdge-tmsg-flush-dynpar0-thread32 |
        | testSingleEdge-tmsg-flush-dynpar1-3cpu |
        | testSingleEdge-tmsg-flush-dynpar1-3cpu-thread32 |
        | testSingleEdge-tmsg-flush-dynpar1 |
        | testSingleEdge-tmsg-flush-dynpar1-thread32 |
        | testSingleEdge-tmsg-flush-reference |
        | testSingleEdge-tmsg-flush-reference-thread32 |
        | testSingleEdge-tmsg-global-defdst |
        | testSingleEdge-tmsg-global-dynpar0 |
        | testSingleEdge-tmsg-global-dynpar1 |
        | testSingleEdge-tmsg-global-reference |
        | testSingleEdge-tmsg-noop-defdst |
        | testSingleEdge-tmsg-noop-dynpar0-3cpu |
        | testSingleEdge-tmsg-noop-dynpar0-3cpu-thread32 |
        | testSingleEdge-tmsg-noop-dynpar0 |
        | testSingleEdge-tmsg-noop-dynpar0-thread32 |
        | testSingleEdge-tmsg-noop-dynpar1-3cpu |
        | testSingleEdge-tmsg-noop-dynpar1-3cpu-thread32 |
        | testSingleEdge-tmsg-noop-dynpar1 |
        | testSingleEdge-tmsg-noop-dynpar1-thread32 |
        | testSingleEdge-tmsg-noop-reference |
        | testSingleEdge-tmsg-noop-reference-thread32 |
        | testSingleEdge-tmsg-origin-defdst |
        | testSingleEdge-tmsg-origin-dynpar0-3cpu |
        | testSingleEdge-tmsg-origin-dynpar0-3cpu-thread32 |
        | testSingleEdge-tmsg-origin-dynpar0 |
        | testSingleEdge-tmsg-origin-dynpar0-thread32 |
        | testSingleEdge-tmsg-origin-dynpar1-3cpu |
        | testSingleEdge-tmsg-origin-dynpar1-3cpu-thread32 |
        | testSingleEdge-tmsg-origin-dynpar1 |
        | testSingleEdge-tmsg-origin-dynpar1-thread32 |
        | testSingleEdge-tmsg-origin-reference |
        | testSingleEdge-tmsg-origin-reference-thread32 |
        | testSingleEdge-tmsg-startthread-defdst |
        | testSingleEdge-tmsg-startthread-dynpar0-3cpu |
        | testSingleEdge-tmsg-startthread-dynpar0-3cpu-thread32 |
        | testSingleEdge-tmsg-startthread-dynpar0 |
        | testSingleEdge-tmsg-startthread-dynpar0-thread32 |
        | testSingleEdge-tmsg-startthread-dynpar1-3cpu |
        | testSingleEdge-tmsg-startthread-dynpar1-3cpu-thread32 |
        | testSingleEdge-tmsg-startthread-dynpar1 |
        | testSingleEdge-tmsg-startthread-dynpar1-thread32 |
        | testSingleEdge-tmsg-startthread-reference |
        | testSingleEdge-tmsg-startthread-reference-thread32 |
        | testSingleEdge-tmsg-switch-defdst |
        | testSingleEdge-tmsg-switch-dynpar0-3cpu |
        | testSingleEdge-tmsg-switch-dynpar0-3cpu-thread32 |
        | testSingleEdge-tmsg-switch-dynpar0 |
        | testSingleEdge-tmsg-switch-dynpar0-thread32 |
        | testSingleEdge-tmsg-switch-dynpar1-3cpu |
        | testSingleEdge-tmsg-switch-dynpar1-3cpu-thread32 |
        | testSingleEdge-tmsg-switch-dynpar1 |
        | testSingleEdge-tmsg-switch-dynpar1-thread32 |
        | testSingleEdge-tmsg-switch-reference |
        | testSingleEdge-tmsg-switch-reference-thread32 |
        | testSingleEdge-tmsg-tmsg-defdst |
        | testSingleEdge-tmsg-tmsg-dynpar0-3cpu |
        | testSingleEdge-tmsg-tmsg-dynpar0-3cpu-thread32 |
        | testSingleEdge-tmsg-tmsg-dynpar0 |
        | testSingleEdge-tmsg-tmsg-dynpar0-thread32 |
        | testSingleEdge-tmsg-tmsg-dynpar1-3cpu |
        | testSingleEdge-tmsg-tmsg-dynpar1-3cpu-thread32 |
        | testSingleEdge-tmsg-tmsg-dynpar1 |
        | testSingleEdge-tmsg-tmsg-dynpar1-thread32 |
        | testSingleEdge-tmsg-tmsg-reference |
        | testSingleEdge-tmsg-tmsg-reference-thread32 |
        | testSingleEdge-tmsg-wait-defdst |
        | testSingleEdge-tmsg-wait-dynpar0-3cpu |
        | testSingleEdge-tmsg-wait-dynpar0-3cpu-thread32 |
        | testSingleEdge-tmsg-wait-dynpar0 |
        | testSingleEdge-tmsg-wait-dynpar0-thread32 |
        | testSingleEdge-tmsg-wait-dynpar1-3cpu |
        | testSingleEdge-tmsg-wait-dynpar1-3cpu-thread32 |
        | testSingleEdge-tmsg-wait-dynpar1 |
        | testSingleEdge-tmsg-wait-dynpar1-thread32 |
        | testSingleEdge-tmsg-wait-reference |
        | testSingleEdge-tmsg-wait-reference-thread32 |
        | testSingleEdge-wait-blockalign-defdst |
        | testSingleEdge-wait-blockalign-target |
        | testSingleEdge-wait-block-defdst |
        | testSingleEdge-wait-block-target |
        | testSingleEdge-wait-flow-defdst |
        | testSingleEdge-wait-flush-defdst |
        | testSingleEdge-wait-global-defdst |
        | testSingleEdge-wait-noop-defdst |
        | testSingleEdge-wait-origin-defdst |
        | testSingleEdge-wait-startthread-defdst |
        | testSingleEdge-wait-switch-defdst |
        | testSingleEdge-wait-tmsg-defdst |
        | testSingleEdge-wait-wait-defdst |